//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace UDS.wsms {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="smsSoap", Namespace="http://tempuri.org/")]
    public class sms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public sms() {
            this.Url = "http://192.168.0.244/wsms/sms.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SendMsg(string Msg, string MobileNo, int MsgIndex, bool IsZh) {
            object[] results = this.Invoke("SendMsg", new object[] {
                        Msg,
                        MobileNo,
                        MsgIndex,
                        IsZh});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendMsg(string Msg, string MobileNo, int MsgIndex, bool IsZh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendMsg", new object[] {
                        Msg,
                        MobileNo,
                        MsgIndex,
                        IsZh}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSendMsg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
